export {
  useLogin,
  useCurrentUser,
  useAcademicYear,
  useDepartments,
  useSubjects,
  useClasses,
  useTeacherAssignments,
  useMyAssignments,
  useAllStudents,
  useStudentProfile,
  useCreateMutation,
  useUpdateMutation,
} from './api/authAcademics';

export {
  useStudentTermGrades,
  useGradeEntry,
  useMissingObservations,
  useClassPerformance,
  useUpsertGrade,
  useBulkUpsertGrades,
  useCorrectGrade,
  useLockGrade,
  useUnlockGrade,
  useApproveGrade,
  useBulkApproveGrades,
} from './api/grading';

export {
  useStudentNotifications,
  useAnalyticsPulse,
  useSendNotification,
  useMarkNotificationRead,
  useEmergencyBroadcast,
} from './api/comms';

export {
  useStudentReportCard,
  useStudentTranscript,
  useGenerateReport,
  useReleaseReportCard,
  useVerifyDocument,
} from './api/reports';

export {
  usePromotionHistory,
  useAcademicYears,
  useArchiveStats,
  usePromoteStudent,
} from './api/archive';

export {
  useTeacherClasses,
  useTeacherAnalytics,
  useTeacherSupportObservations,
  useTeacherGradeIssues,
  useTeacherGradeIssueStatusMeta,
  useTeacherTimetable,
  useTeacherSettingsClasses,
  useTeacherNotificationPreferences,
  useTeacherProfile,
  useTeacherGradingStudents,
  useTeacherSubjectConfig,
  useTeacherGradingStatusMeta,
  useTeacherGradingFilterOptions,
  useTeacherGradeConfig,
  useSubmitGradeRevision,
  useUpdateGradeRevision,
} from './api/teacher';

export {
  useAllStaff,
  useCreateStaff,
  useCreateStudent,
  useCreateParent,
  useUpdateStudentProfile,
  useDeactivateUser,
  useActiveYear,
  useAllDepartments,
  useAllSubjects,
  useAllClasses,
  useCreateYear,
  useActivateYear,
  useCreateTerm,
  useActivateTerm,
  useCreateDepartment,
  useCreateSubject,
  useCreateClass,
  useAssignClassTeacher,
  useAssignTeacher,
  useGenerateReportCard,
  useBatchGenerateReportCards,
  useBuildTranscript,
  usePromoteStudent as useAdminPromoteStudent,
  useDatabaseHealth,
  useUnreadNotifications,
  useTickets,
  useUpdateTicketStatus,
  useGradeEntry as useAdminGradeEntry,
  useMissingObservations as useAdminMissingObservations,
  useClassPerformance as useAdminClassPerformance,
  useStudentTermGrades as useAdminStudentTermGrades,
  useTimetableEntries,
  useMySchedule,
  useClashes,
  useCreateTimetableEntry,
  useUpdateTimetableEntry,
  useDeleteTimetableEntry,
  useStudentInterventions,
  useStudentBehavior,
  useCreateBehavior,
} from './api/admin';
