export {
  useLogin,
  useCurrentUser,
  useAcademicYear,
  useDepartments,
  useSubjects,
  useClasses,
  useTeacherAssignments,
  useMyAssignments,
  useAllStudents,
  useStudentProfile,
  useCreateMutation,
  useUpdateMutation,
} from './api/authAcademics';

export {
  useStudentTermGrades,
  useGradeEntry,
  useMissingObservations,
  useClassPerformance,
  useUpsertGrade,
  useBulkUpsertGrades,
  useCorrectGrade,
  useLockGrade,
  useUnlockGrade,
  useApproveGrade,
  useBulkApproveGrades,
} from './api/grading';

export {
  useStudentNotifications,
  useAnalyticsPulse,
  useSendNotification,
  useMarkNotificationRead,
  useEmergencyBroadcast,
} from './api/comms';

export {
  useStudentReportCard,
  useStudentTranscript,
  useGenerateReport,
  useReleaseReportCard,
  useVerifyDocument,
} from './api/reports';

export {
  usePromotionHistory,
  useAcademicYears,
  useArchiveStats,
  usePromoteStudent,
  useSearchVault,
} from './api/archive';

export {
  useTeacherClasses,
  useTeacherAnalytics,
  useTeacherSupportObservations,
  useTeacherGradeIssues,
  useTeacherGradeIssueStatusMeta,
  useTeacherTimetable,
  useTeacherSettingsClasses,
  useTeacherNotificationPreferences,
  useTeacherProfile,
  useTeacherGradingStudents,
  useTeacherSubjectConfig,
  useTeacherGradingStatusMeta,
  useTeacherGradingFilterOptions,
  useTeacherGradeConfig,
  useSubmitGradeRevision,
  useUpdateGradeRevision,
} from './api/teacher';

export {
  useApprovals,
  useResolveApproval,
} from './api/admin';

export {
   useAllStaff,
   useCreateStaff,
   useCreateStudent,
   useBatchImportStudents,
   useCreateParent,
   useAllParents,
   useUpdateStudentProfile,
   useDeactivateUser,
   useActiveYear,
   useAllDepartments,
   useAllSubjects,
   useAllClasses,
   useCreateYear,
   useActivateYear,
   useCreateTerm,
   useActivateTerm,
   useCreateDepartment,
   useCreateSubject,
   useCreateClass,
   useAssignHOD,
   useDeleteDepartment,
   useTransferTeacher,
   useAssignClassTeacher,
   useAssignTeacher,
   useGenerateReportCard,
   useBatchGenerateReportCards,
   useBuildTranscript,
   usePromoteStudent as useAdminPromoteStudent,
   useDatabaseHealth,
   useUnreadNotifications,
   useTickets,
   useUpdateTicketStatus,
   useGradeEntry as useAdminGradeEntry,
   useMissingObservations as useAdminMissingObservations,
   useClassPerformance as useAdminClassPerformance,
   useStudentTermGrades as useAdminStudentTermGrades,
    useTimetableEntries,
    useMySchedule,
    useClashes,
    useCreateTimetableEntry,
    useUpdateTimetableEntry,
    useDeleteTimetableEntry,
    useClassAssignments,
   useStudentInterventions,
   useStudentBehavior,
   useCreateBehavior,
   useAdminAuditLogs,
   useResetStaffCredentials,
   useSystemFreeze,
   useToggleSystemFreeze,
 useLockTerm,
      useUnlockTerm,
      useGradingRules,
      useUpdateGradingRules,
      useComplianceWarnings,
      usePromoteLevel,
    useArchiveYear,
    useTransferStudents,
    useUpdateClassCapacity,
    useRebalanceHouses,
    useDissolveClass,
    useDeployCurriculumMapping,
  } from './api/admin';
