export {
  useAcademicYear,
  useDepartments,
  useSubjects,
  useClasses,
  useTeacherAssignments,
  useMyAssignments,
  useAllStudents,
  useStudentProfile,
  useCreateMutation,
  useUpdateMutation,
} from './api/authAcademics';

export {
  useStudentTermGrades,
  useGradeEntry,
  useMissingObservations,
  useClassPerformance,
  useUpsertGrade,
  useBulkUpsertGrades,
  useCorrectGrade,
  useLockGrade,
  useUnlockGrade,
  useApproveGrade,
  useBulkApproveGrades,
} from './api/grading';

export {
  useStudentNotifications,
  useAnalyticsPulse,
  useSendNotification,
  useMarkNotificationRead,
  useEmergencyBroadcast,
} from './api/comms';

export {
  useStudentReportCard,
  useStudentTranscript,
  useGenerateReport,
  useReleaseReportCard,
  useVerifyDocument,
} from './api/reports';

export {
  usePromotionHistory,
  useAcademicYears,
  useArchiveStats,
  usePromoteStudent,
  useSearchVault,
  useClassBenchmarks,
} from './api/archive';

export {
  useTeacherClasses,
  useTeacherAnalytics,
  useTeacherSupportObservations,
  useTeacherGradeIssues,
  useTeacherGradeIssueStatusMeta,
  useTeacherTimetable,
  useTeacherSettingsClasses,
  useTeacherNotificationPreferences,
  useTeacherProfile,
  useTeacherGradingStudents,
  useTeacherSubjectConfig,
  useTeacherGradingStatusMeta,
  useTeacherGradingFilterOptions,
  useTeacherGradeConfig,
  useSubmitGradeRevision,
  useUpdateGradeRevision,
} from './api/teacher';

export {
  useStudentCount,
  useStudentBoarderStats,
  useStaffCount,
  useAllStaff,
  useCreateStaff,
  useCreateStudent,
  useBatchImportStudents,
  useCreateParent,
  useAllParents,
  useUpdateStudentProfile,
  useDeactivateUser,
  useActiveYear,
  useAllDepartments,
  useDepartment,
  useAllSubjects,
  useAllClasses,
  useCreateYear,
  useActivateYear,
  useCreateTerm,
  useActivateTerm,
  useCreateDepartment,
  useCreateSubject,
  useUpdateSubject,
  useCreateClass,
  useUpdateClass,
  useAssignHOD,
  useDeleteDepartment,
  useTransferTeacher,
  useAssignClassTeacher,
  useAssignTeacher,
  useGenerateReportCard,
  useBatchGenerateReportCards,
  useBuildTranscript,
  usePromoteStudent as useAdminPromoteStudent,
  useDatabaseHealth,
  useUnreadNotifications,
  useTickets,
  useUpdateTicketStatus,
  useGradeEntry as useAdminGradeEntry,
  useMissingObservations as useAdminMissingObservations,
  useClassPerformance as useAdminClassPerformance,
  useStudentTermGrades as useAdminStudentTermGrades,
   useTimetableEntries,
   useMySchedule,
   useClashes,
    useCreateTimetableEntry,
    useUpdateTimetableEntry,
    useDeleteTimetableEntry,
    useBroadcastTimetable,
    useFinalizeTimetable,
    useClassAssignments,
    useTimeSlots,
    useCreateTimeSlot,
    useUpdateTimeSlot,
    useDeleteTimeSlot,
    useReorderTimeSlots,
  useStudentInterventions,
  useStudentBehavior,
  useCreateBehavior,
  useAdminAuditLogs,
  useResetStaffCredentials,
  useBulkImportStaff,
  useUpdateStaff,
  useSystemFreeze,
  useToggleSystemFreeze,
 useLockTerm,
    useUnlockTerm,
    useGradingRules,
    useUpdateGradingRules,
    useComplianceWarnings,
    useTermSummary,
    usePromoteLevel,
   useArchiveYear,
   useTransferStudents,
   useUpdateClassCapacity,
   useRebalanceHouses,
   useDissolveClass,
     useDeployCurriculumMapping,
     useCurriculumMatrix,
     useUpsertCurriculumMapping,
     useRemoveCurriculumMapping,
      useBulkUpsertCurriculum,
      useDeployCurriculum,
      useCurriculumDeploymentStatus,
      useClassesWithStudents,
  useApprovals,
  useResolveApproval,
} from './api/admin';
